---
ID: "CDA5ECB6-5E63-456D-A726-8202BBB5D78E"
Parent: "69403688-7243-4F78-9CA2-25DC8333CE35"
Template: "69403688-7243-4F78-9CA2-25DC8333CE35"
Path: "/sitecore/templates/Project/click-click-launch/Components/Banners/Flex Cards/Flex Card/__Standard Values"
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A053ED9F-4099-4682-9411-2B4C98E481E4}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "CDA5ECB6-5E63-456D-A726-8202BBB5D78E"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250115T120000Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "CDA5ECB6-5E63-456D-A726-8202BBB5D78E"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250115T120000Z
